### ISSUE TITLE
firefly mutil blockchain config

### ISSUE THREAD

**Issue by jaylu163** [hyperledger/firefly#1041]
it is my firefly.core.yaml
```
plugins:
  blockchain:
    - name: ethereum
      type: ethereum
      ethereum:
        ethconnect:
          url: http://localhost:8080 #
          topic: "0"
   
    - name: fabric
      type: fabric
      fabric:
        fabconnect:
          url: http://localhost:8080
          topic: chain1
          channel: ""
          chaincode: ""
  database:
    - name: sqlite3
      type: sqlite3
      sqlite3:
        url: mydb?_busy_timeout=5000
        migrations:
          auto: true
```
I konw ,is not right

how I want to do ??

thk
