### ISSUE TITLE
"Work with remote Hyperledger Fabric Network" , how should i do ,to resolve this error

### ISSUE THREAD

**Issue by 499909744** [hyperledger/firefly#1061]
### fabric-ca server is a exist server ,has used serveral months; we use the fabric-gateway visit is ok;

```
organizations/peerOrganizations/org1.yytest.cn/
├── ca
│   └── ca-cert.pem
├── client
│   └── admin
│       ├── fabric-ca-client-config.yaml
│       └── msp
├── crypto
│   ├── ca-cert.pem
│   ├── fabric-ca-server-config.yaml
│   ├── fabric-ca-server.db
│   ├── IssuerPublicKey
│   ├── IssuerRevocationPublicKey
│   ├── msp
│   │   ├── cacerts
│   │   ├── config.yaml
│   │   ├── keystore
│   │   ├── signcerts
│   │   └── user
│   └── tls-cert.pem
├── msp
│   ├── admincerts
│   │   └── ca-cert.pem
│   ├── cacerts
│   │   └── 0-0-0-0-7054.pem
│   ├── config.yaml
│   └── tlscacerts
│       └── tls-ca-cert.pem
├── peers
│   ├── peer1.org1.yytest.cn
│   │   ├── fabric-ca-client-config.yaml
│   │   ├── msp
│   │   └── tls
│   └── peer2.org1.yytest.cn
│       ├── fabric-ca-client-config.yaml
│       ├── msp
│       └── tls
├── tlsca
│   └── tls-ca-cert.pem
└── users
    ├── Admin@org1.yytest.cn
    │   ├── fabric-ca-client-config.yaml
    │   └── msp
    └── User@org1.yytest.cn
        ├── fabric-ca-client-config.yaml
        └── msp
```

**docker-compose.override.yaml**

```
# Add custom config overrides here
# See https://docs.docker.com/compose/extends
version: "2.1"
services:
  fabconnect_0:
    container_name: yljk_fabconnect_0
    image: ghcr.io/hyperledger/firefly-fabconnect@sha256:0dff97610990414d8ceb24859ced7712fa18b71b1d22b6a6f46fd51266413a22
    command: -f /fabconnect/fabconnect.yaml
    volumes:
      - fabconnect_receipts_0:/fabconnect/receipts
      - fabconnect_events_0:/fabconnect/events
      - /root/.firefly/stacks/yljk/runtime/blockchain/fabconnect.yaml:/fabconnect/fabconnect.yaml
      - /root/.firefly/stacks/yljk/runtime/blockchain/ccp.yaml:/fabconnect/ccp.yaml
      - /root/.firefly/stacks/yljk/organizations:/etc/firefly/organizations
      - firefly_fabric:/etc/firefly

```

### ccp.yaml

```certificateAuthorities:
    org1.yytest.cn:
        tlsCACerts:
            path: /etc/firefly/organizations/peerOrganizations/org1.yytest.cn/crypto/tls-cert.pem
        url: http://192.168.3.61:7054
        registrar:
            enrollId: admin-org1
            enrollSecret: org1AdminPW
```

### [fabconnect_0] container report error:

```Copyright (C) 2021 Kaleido

Licensed under the Apache License, Version 2.0

Version:  (Build Date: 2022-04-26T19:04:41Z)

time="2022-09-16T10:56:45Z" level=info msg="Using config file: /fabconnect/fabconnect.yaml\n"

 [fabsdk/core] 2022/09/16 10:56:45 UTC - cryptosuite.GetDefault -> INFO No default cryptosuite found, using default SW implementation

 [fabsdk/fab] 2022/09/16 10:56:45 UTC - fab.detectDeprecatedNetworkConfig -> WARN Getting orderers from endpoint config channels.orderer is deprecated, use entity matchers to override orderer configuration

 [fabsdk/fab] 2022/09/16 10:56:45 UTC - fab.detectDeprecatedNetworkConfig -> WARN visit https://github.com/hyperledger/fabric-sdk-go/blob/master/test/fixtures/config/overrides/local_entity_matchers.yaml for samples

Error: Identity manager creation failed. org config retrieval failed```
