### ISSUE TITLE
v1.3.1 Performance Testing 

### ISSUE THREAD

**Issue by EnriqueL8** [hyperledger/firefly#1540]
Run the performance tests using the perf-cli, similar to https://github.com/hyperledger/firefly/issues/1470#issuecomment-2077567912

**Comment by EnriqueL8** [comment]
# Run against 1.3.1

```
stackJSONPath: /home/ubuntu/.firefly/stacks/newstack/stack.json

wsConfig:
  wsPath: /ws
  readBufferSize: 16000
  writeBufferSize: 16000
  initialDelay: 250ms
  maximumDelay: 30s
  initialConnectAttempts: 5
  heartbeatInterval: 5s

instances:
  - name: long-run
    tests: [{"name": "msg_broadcast", "workers":50},{"name": "msg_private", "workers":50},{"name": "blob_broadcast", "workers":30},{"name": "blob_private", "workers":30},{"name": "custom_ethereum_contract", "workers":20},{"name": "token_mint", "workers":10}]
    length: 500h
    sender: 0
    recipient: 1
    messageOptions:
      longMessage: false
    tokenOptions:
      tokenType: fungible
    contractOptions: {"address": "0x2715cc29d158e2d5261cb33a2eec0c6789e7eb6d"}
```
FireFly git commit:
```
3a2d40cca759c761ff0bba839ac582da163453d2
```
```
