### ISSUE TITLE
Hardening: Run an Ethereum long run test at baseline throughput for a week

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#563]

**Comment by awrichar** [comment]
New Discord thread for runs in preparation for v1.1: https://discord.com/channels/905194001349627914/1004496575059476570

**Comment by awrichar** [comment]
# Run Report
Started: 8/17/22
Duration: ~92 hours
Git commit: d54355dc8d062930286a419140dceafb82d42903

**Node Configuration**
2 FireFly nodes on one virtual server (EC2 m4.xlarge)
Entire FireFly stack is local to the server (ie both blockchains, Postgres databases, etc)
Maximum time to confirm before considering failure = 1 minute

<details>
  <summary>Configuration details</summary>

core-config.yml
```
log:
        level: debug
broadcast:
        batch:
                size: 200
                timeout: 1s
privatemessaging:
        batch:
                size: 200
                timeout: 1s
message:
        writer:
                count: 5
download:
        worker:
                count: 100
publicstorage:
                ipfs:
                        api:
                                requestTimeout: 2s
                        gateway:
                                requestTimeout: 2s
```

ethconnect.yml
```
rest:
  rest-gateway:
    maxTXWaitTime: 120
    maxInFlight: 200
    alwaysManageNonce: true
    attemptGapFill: true
    sendConcurrency: 3
    gasEstimationFactor: 2.0
```

instances.yml
```
stackJSONPath: /home/ubuntu/.firefly/stacks/v11rc1/stack.json

wsConfig:
  wsPath: /ws
  readBufferSize: 16000
  writeBufferSize: 16000
  initialDelay: 250ms
  maximumDelay: 30s
  initialConnectAttempts: 5
  heartbeatInterval: 5s

instances:
  - name: long-run
    tests: [{"name": "msg_broadcast", "workers":50},{"name": "msg_private", "workers":50},{"name": "blob_broadcast", "workers":30},{"name": "blob_private", "workers":30},{"name": "custom_ethereum_contract", "workers":20},{"name": "token_mint", "workers":10}]
    length: 500h
    sender: 0
    recipient: 1
    messageOptions:
      longMessage: false
    tokenOptions:
      tokenType: fungible
    contractOptions: {"address": "0xc39c9b8384d682a17b74d9454af3eeefff919434"}
```

</details>

**Results**

- Broadcast messages: 3,899,387
- Private messages: 5,077,650
- Token mints: 381,309
- Contract invocations: 2,090,955
- No errors

Run terminated when disk space ran out and geth node terminated.

**Run Graph**
<img width="1590" alt="perf1" src="https://user-images.githubusercontent.com/1993829/185959247-40d98a8b-d53e-4ffd-8c51-b9edc8842071.png">
<img width="1592" alt="perf2" src="https://user-images.githubusercontent.com/1993829/185959275-d97d6589-ef82-4d98-a76b-8cb4bbe394b7.png">
