### ISSUE TITLE
New Orgs / Nodes Rejecting Previous Node Identity Claims

### ISSUE THREAD

**Issue by hfuss** [hyperledger/firefly#692]
## Description

When creating multi-org networks via the Helm chart, we would stand up the first node for an org, then stand up a new node / org, then another and so on (a bit different from how the CLI creates networks). In the new nodes, we would observe them rejecting the first org's node identity claim messages due to:

```
[2022-04-11T17:19:21.074Z]  WARN poc4-par2-firefly: Unable to process identity claim 564be456-7834-4218-84b9-1a82c9011270: FF10214: Identity '8e8b6544-df58-43fe-935e-f0078b760e7d' not found in identity chain for did:firefly:node/poc4-par1-firefly 'd81e6067-bb73-4613-83c3-49b4a0a08051' dbtx=85C5Fddx role=aggregator
```

The ethconnects were in catchup mode, so the other nodes were presumed to be processing the org and node identity claim messages in the same batchpin. So it appears to be a bug in the logic where the aggregator does not account for needing to process org identity claims before node identity claims within the same batch. 

## Other Info

FireFly Version: `1.0.0-rc3`
Ethconnect Version: `v3.1.5`
Blockchain Provider: `Quorum v21.10.0 (Geth v1.9.25)`

Relevant Ethconnect Configuration:

```yaml
rest:
  rest-gateway:
    leveldb:
      path: "/qdata/ethconnect/receiptsdb"
      queryLimit: 100
    alwaysManageNonce: false
    maxTXWaitTime: 120
    openapi:
      storagePath: "/qdata/ethconnect/openapi"
      eventsDB: "/qdata/ethconnect/eventsdb"
      catchupModeBlockGap: 10000
      catchupModePageSize: 10000
```

## Logs

First Org / Node : [poc4-par1.log](https://github.com/hyperledger/firefly/files/8466801/poc4-par1.log)

Other Orgs / Nodes:
* [poc4-par2.log](https://github.com/hyperledger/firefly/files/8466802/poc4-par2.log)
* [poc4-par3.log](https://github.com/hyperledger/firefly/files/8466803/poc4-par3.log)
