### ISSUE TITLE
Structured JSON Logging

### ISSUE THREAD

**Issue by hfuss** [hyperledger/firefly#713]
FireFly is using https://github.com/sirupsen/logrus which is great. However, when integrating with log aggregation systems which allow searching across multiple indexed fields of documents, i.e. OpenSearch, the current experience requires doing inefficient searches of message IDs, etc. within the log message itself. Instead, we can structure the logs as JSON so certain useful / often searched pieces of metadata within logs can be included as separate fields and therefore more easily searchable. Such pieces of metadata can be very high in cardinality which serves as a great compliment to our Prometheus metrics which cannot be as high in cardinality without exploding timeseries costs.

To close this issue, we should achieve two things:

1. Offer new [`log`](https://hyperledger.github.io/firefly/reference/config.html#log) options for enabling JSON logs, which just sets the logrus formatter to the `JSONFormatter` behind the scenes: https://github.com/sirupsen/logrus#environments
2. Refactor log statements throughout the code base to use `WithFields` which will help improve log clarity in the unstructured case, while simultaneously enabling searchable fields when using structured logs: https://github.com/sirupsen/logrus#fields

**Comment by hfuss** [comment]
So a few things:
1. We were using `WithFields` in a bunch of places to include details like `role` which indicates which subsystem of FireFly was logging in certain cases i.e. `batchmgr`, `event-manager`, and `ep*`. Including additional fields like `msgID` is reserved for fixing on an individual log statement basis as part of other PRs and is considered out-of-scope of this issue.
2. With #737 one can now enable JSON logs w/ `log.json.enabled`. Using our [Helm chart](https://github.com/hyperledger/firefly-helm-charts/tree/main/charts/firefly) with the [`filebeat` chart](https://github.com/elastic/helm-charts/tree/main/filebeat), we got structured logging in OpenSearch working via the following config:
  ```yaml
 # filebeat Helm values
  filebeatConfig:
    filebeat.yml: |-
      filebeat:
        autodiscover:
          providers:
            - type: kubernetes
              node: ${NODE_NAME}
              hints:
                enabled: true
                default_config:
                  type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}
  # ...
  
  # firefly Helm values
  core:
    extraEnv:
      - name: FIREFLY_LOG_JSON_ENABLED
         value: "true"
    podAnnotations:
      co.elastic.logs/json.keys_under_root: "true"
      co.elastic.logs/json.add_error_key: "true"
      co.elastic.logs/json.message_key: message
      co.elastic.logs/json.overwrite_keys: "true"
  ```
